name: Django-ORM-Course

services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432" # opening 5432 port and mapping that across to the container

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    ports:
    - "8000:8000"
    command: >
      sh -c "
        python manage.py runserver 0.0.0.0:8000
      "
